### ISSUE TITLE
Отсутствует папка "./private"

### ISSUE THREAD

**Issue by PavelMishin** [vedees/filmlibrary#1]
Привет, после просмотра видео на твоём канале решил посмотреть проект, а тут вообще совершенно другая  структура, непонятно как сформированная. Почему например user, time, tasks и tags выпилены из store в отдельную папку ./private и как без неё запустить проект? И где вообще искать пояснения к изменениям по сравнению с видео, например nuxt, тэмплейты, структура?

**Comment by vedees** [comment]
Привет, переключи бранч на vue old там все, что было в видео
